### PR TITLE
Fix: panic when random_kill is specified in local tests

### LINKED ISSUE #237: don't panic when random_kill is specified in local tests
## Bug Report

**What did you do?**

Use `LocalClusterProvisioner` as service provisoner, and then test a case with `random_kill` specified. 

**What did you expect to see?**
Although `random_kill` is not supported in local mode, it's better not to panic for tipocket.

**What did you see instead?**
However tipocket paniced:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x166c7f6]

goroutine 217 [running]:
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate(0x204f4a0, 0xc00017e240, 0x0, 0x0, 0x20133e0, 0xc0007f8000, 0xc000899470, 0xc, 0xc0007b6090, 0xc0007b4040, ...)
        /home/qupeng/.go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/controller/controllerutil/controllerutil.go:142 +0x96
github.com/pingcap/tipocket/pkg/nemesis.(*Chaos).ApplyPodChaos(0xc0005fd950, 0x204f4a0, 0xc00017e240, 0xc0007f8000, 0x1d55e08, 0x0)
        /home/qupeng/.go/src/github.com/pingcap/tipocket/pkg/nemesis/client.go:55 +0xbe
github.com/pingcap/tipocket/pkg/nemesis.kill.Invoke(0xc0005fd950, 0x204f4a0, 0xc00017e240, 0xc0001f20a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/qupeng/.go/src/github.com/pingcap/tipocket/pkg/nemesis/kill.go:153 +0x1ef
github.com/pingcap/tipocket/pkg/control.(*Controller).onNemesis(0xc00028a1e0, 0x204f4a0, 0xc00017e240, 0xc0007ae050)
        /home/qupeng/.go/src/github.com/pingcap/tipocket/pkg/control/control.go:459 +0x335
github.com/pingcap/tipocket/pkg/control.(*Controller).dispatchNemesis.func1(0xc0004b3f68, 0xc00028a1e0)
        /home/qupeng/.go/src/github.com/pingcap/tipocket/pkg/control/control.go:418 +0x45
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0007b6030, 0xc0007b6060)
        /home/qupeng/.go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/qupeng/.go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by mahjonp**
Signed-off-by: mahjonp <junpeng.man@gmail.com>

### What problem does this PR solve? 

Close #237 

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

File: pkg/control/control.go [hunk 1]
```diff
@@ -455,6 +455,7 @@ func (c *Controller) onNemesis(ctx context.Context, op *core.NemesisOperation) {
 	nemesis := core.GetNemesis(string(op.Type))
 	if nemesis == nil {
 		log.Errorf("nemesis %s is not registered", op.Type)
+		time.Sleep(30 * time.Second)
```
Comment (yeya24) [inline pkg/control/control.go:458]: Why need to wait 30s?

Comment (mahjonp) [reply pkg/control/control.go:458]: Because the next round of `OnNemesis` starts immediately after current round returns, so a sleep is needed otherwise there will be a lot of logs.

Comment (yeya24) [reply pkg/control/control.go:458]: Make sense.
